name: Fabrica Automatica de Vita

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Usamos un contenedor pre-hecho por la comunidad que ya tiene VitaSDK e instalado vita2d
    container: vitasdk/vitasdk:latest

    steps:
    - name: Descargar codigo del usuario
      uses: actions/checkout@v4

    - name: Compilar el Port y empaquetar VPK
      run: |
        # Compilamos nuestro main.c usando las herramientas que ya viven dentro del contenedor
        arm-vita-eabi-gcc main.c -o amongus.elf -lvita2d -lSceDisplay_stub -lSceGxm_stub -lSceSysmodule_stub -lSceCtrl_stub -lScePgf_stub -lm
        
        # Generamos el ejecutable seguro de la Vita
        vita-make-fself amongus.elf eboot.bin
        
        # Creamos el archivo de informacion de la burbuja
        vita-mksfo "Among Us Vita Port" param.sfo
        
        # Empaquetamos todo en el instalador .vpk
        vita-pack-vpk -s param.sfo -b eboot.bin amongus_2020.vpk

    - name: Subir el instalador .VPK final
      uses: actions/upload-artifact@v4
      with:
        name: AmongUs_Vita_Instalador
        path: amongus_2020.vpk