name: Fabrica Automatica de Vita

on:
push:
branches: [ main ] # Se activa con cualquier cambio guardado en la rama principal

jobs:
build:
runs-on: ubuntu-latest # Usamos una maquina limpia de Ubuntu en la nube

steps:
- name: 1. Descargar codigo del usuario
  uses: actions/checkout@v4

- name: 2. Mostrar archivos (Para asegurar que main.c esta en su lugar)
  run: |
    echo "Verificando archivos en la raiz:"
    ls -la

- name: 3. Compilar usando Docker de forma controlada
  run: |
    # Levantamos el contenedor oficial de VitaSDK
    # Montamos nuestra carpeta de trabajo en '/build' y forzamos a que esa sea la ruta activa
    docker run --rm -v ${{ github.workspace }}:/build -w /build vitasdk/vitasdk:latest sh -c "
      echo '=== Iniciando Compilacion en la Nube ==='
      
      # Compilamos enlazando las librerias graficas necesarias
      arm-vita-eabi-gcc main.c -o amongus.elf -lvita2d -lSceDisplay_stub -lSceGxm_stub -lSceSysmodule_stub -lSceCtrl_stub -lScePgf_stub -lm
      
      # Convertimos el ELF en ejecutable binario de PS Vita
      vita-make-fself amongus.elf eboot.bin
      
      # Creamos el archivo de metadatos (Titulo y ID de la aplicacion)
      vita-mksfo 'Among Us Vita Port' param.sfo
      
      # Empaquetamos todo dentro del archivo .VPK final
      vita-pack-vpk -s param.sfo -b eboot.bin
